// solana/app/src/routes/read_solana/+page.svelte
<script lang="ts">
	import * as Web3 from "@solana/web3.js"
	let address = "Jkrq3ZN6H6SaaGudG8KMKY587BZ8gczxNBuzfaB9JGc" // my address
	let loading = false
	let isExecutable = false
	let balanceInfoSet = false
	let balanceValue = 0
	let setAddress = ""

	async function getBalance() {
		try {
			loading = true
			const key = new Web3.PublicKey(address)
			const connection = new Web3.Connection(Web3.clusterApiUrl("devnet"))
			const balance = await connection.getBalance(key)
			balanceValue = balance / Web3.LAMPORTS_PER_SOL
			const info = await connection.getAccountInfo(key)
			if (info) isExecutable = info.executable
			setAddress = address
			balanceInfoSet = true
		} catch (error) {
			console.log(error)
			isExecutable = false
			balanceInfoSet = false
			balanceValue = 0
		} finally {
			loading = false
		}
	}

	type AirdropStatus = "none" | "loading" | "success" | "error"
	let airdropStatus: AirdropStatus = "none"
	async function airdrop() {
		try {
			airdropStatus = "loading"
			const connection = new Web3.Connection(Web3.clusterApiUrl("devnet"))
			const key = new Web3.PublicKey(address)
			await connection.requestAirdrop(key, Web3.LAMPORTS_PER_SOL * 1)
			airdropStatus = "success"
		} catch (error) {
			console.log(error)
			airdropStatus = "error"
		}
	}
</script>

<div class="container flex flex-col justify-center">
	<nav>
		<a href="/">⬅️ Home</a>
	</nav>
	<h1>Get The Balance of a Solana Address</h1>
	<label for="address">Solana Address (Devnet)</label>
	<input id="address" type="text" bind:value={address} />
	<button aria-busy={loading} on:click={getBalance} disabled={loading}>
		{loading ? "Getting balance..." : "Get Balance"}
	</button>
	{#if balanceInfoSet}
		<p class="mb-1">Address: <strong>{setAddress}</strong></p>
		<p class="mb-1">The balance is: <strong>{balanceValue}</strong> SOL</p>
		<p>Is it executable? <strong>{isExecutable ? "Hell Yeah" : "Nope"}</strong></p>
		<hr class="m-2" />
		<button on:click={airdrop} aria-busy={airdropStatus == "loading"}
			>{airdropStatus == "loading" ? "Airdropping..." : "Airdrop 1 SOL"}</button
		>
		{#if airdropStatus == "success"}
			<p>Airdrop successful</p>
		{/if}
	{/if}
</div>

// solana/next-app/src/app/read_solana/page.tsx
"use client"

import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useState } from "react"
import * as web3 from "@solana/web3.js"

export default function ReadSolana() {
	let startingAddress = "Jkrq3ZN6H6SaaGudG8KMKY587BZ8gczxNBuzfaB9JGc" // my address
	const [address, setAddress] = useState(startingAddress)
	const [balance, setBalance] = useState(0)
	const [isExecutable, setIsExecutable] = useState(false)
	const [balanceStatus, setBalanceStatus] = useState("") // "loading" | "success" | "error"
	const [airdropStatus, setAirdropStatus] = useState("") // "loading" | "success" | "error"
	const [airdropSignature, setAirdropSignature] = useState("")

	async function getBalance() {
		try {
			setBalanceStatus("loading")
			const connection = new web3.Connection(web3.clusterApiUrl("devnet"), "confirmed")
			const publicKey = new web3.PublicKey(address)
			const balance = await connection.getBalance(publicKey)
			const info = await connection.getAccountInfo(publicKey)
			setIsExecutable(info!.executable)
			setBalance(balance / web3.LAMPORTS_PER_SOL)
			setBalanceStatus("success")
		} catch (e) {
			alert(e)
			setBalanceStatus("error")
		}
	}

	async function airdrop() {
		try {
			setAirdropStatus("loading")
			const connection = new web3.Connection(web3.clusterApiUrl("devnet"), "confirmed")
			const publicKey = new web3.PublicKey(address)
			const signature = await connection.requestAirdrop(publicKey, web3.LAMPORTS_PER_SOL)
			setAirdropSignature(signature)
			setAirdropStatus("success")
		} catch (e) {
			alert(e)
			setAirdropStatus("error")
		}
	}

	return (
		<>
			<nav>
				<a className="text-blue-500" href="/">
					⬅️ Home
				</a>
			</nav>
			<h3 className="mt-4 text-3xl">Get the balance of a Solana address</h3>
			<Input
				className="my-4 w-1/2"
				onChange={(e) => setAddress(e.target.value)}
				value={startingAddress}
			/>
			<Button className="mb-4" onClick={getBalance}>
				Get balance
			</Button>
			{balanceStatus === "loading" && <p>Loading...</p>}
			{balanceStatus === "success" && (
				<>
					<p className="mt-4">Balance: {balance} SOL</p>
					<p className="my-2">Is executable: {isExecutable ? "Yes" : "No"}</p>
					<Button className="mt-2" onClick={airdrop}>
						Airdrop 1 SOL
					</Button>
					{airdropStatus === "loading" && <p>Loading...</p>}
					{airdropStatus === "success" && (
						<>
							<p className="mt-4">Airdrop signature: {airdropSignature}</p>
							<p className="mt-4">
								Check the transaction on{" "}
								<a
									className="text-blue-500 underline"
									href={`https://explorer.solana.com/tx/${airdropSignature}`}
								>
									Solana Explorer
								</a>
							</p>
						</>
					)}
				</>
			)}
		</>
	)
}
